# Generated by Django 5.1.6 on 2025-03-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blog'),
        ),
    ]
